config/routes.rb
Rails.application.routes.draw do
  root 'lists#index'
  resources :lists do
    resources :reviews, only: [:new, :create]
  end
  resources :reviews, only: [:destroy]
  resources :lists, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/country.rb
class Country < ApplicationRecord
  has_many :reviews

  validates :name, presence: true, uniqueness: true
  validates :description, presence: true

  RATING = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
  validates :rating, inclusion: { in: RATING }
  validates :rating, numericality: { only_integer: true }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :reviews, dependent: :destroy
  has_many :countries, through: :reviews, dependent: :destroy

  validates :name, presence: true, uniqueness: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :list
  belongs_to :country

  validates :country_id, uniqueness: { scope: :list_id}
  validates :comment, length: {minimum: 6}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: %i[ show edit update destroy ]

  def index
    @lists = List.all
  end

  def show
  end

  def new
    @list = List.new
  end

  def create
    @list = List.create(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @list.update!(list_params)
      redirect_to @list
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @list.destroy
    redirect_to lists_path, notice: "List was successfully destroyed."
  end

  private
  def set_list
    @list = List.find(params[:id])
  end

  def list_params
    params.require(:list).permit(:name)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @list = List.find(params[:list_id])
    @review = Review.new
  end

  def create
    @list = List.find(params[:list_id])
    @review = Review.new(review_params)
    @review.list = @list
    if @review.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to list_path(@review.list), status: :see_other
  end

  private
  def review_params
    params.require(:review).permit(:comment, :user_name, :country_id, :list_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TravelList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>

  </head>

  <body>
  <nav class="navbar">
      <%= link_to "all lists", lists_path, class: "btn btn-secondary" %>
      <%= link_to "new list", new_list_path, class: "btn btn-primary" %>
  </nav>
    <%= yield %>
  </body>
</html>

app/views/lists/_form.html.erb
<div class="container">
  <%= simple_form_for(@list) do |f| %>
    <%= f.error_notification %>
    <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

    <div class="form-inputs">
        <%= simple_form_for @list do |f| %>
        <%= f.input :name, placeholder: 'Drama' %>
        <%= f.input :photo, as: :file %>
        <%= f.submit class: 'btn btn-secondary' %>
        <% end %>
    </div>
  <% end %>
</div>

app/views/lists/edit.html.erb
<div class="container">
  <h1>Edit List Name</h1>
  <%= simple_form_for(@list) do |f| %>
    <%= f.error_notification %>
    <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

    <div class="form-inputs">
        <%= simple_form_for @list do |f| %>
        <%= f.input :name, placeholder: 'Drama' %>
        <%= f.submit class: 'btn btn-flat' %>
        <% end %>
    </div>
  <% end %>
</div>

app/views/lists/index.html.erb
<div class="container">
  <h1 class="text-center"><strong>My lists</strong></h1>
</div>

<div class="container">
  <div class="d-flex gap-2">
    <% @lists.each do |list| %>
    <div class="card" style="width: 18rem;">
      <img class="card-img-top" src="..." alt="Card image cap">
      <div class="card-body">
        <h5 class="card-title"> <%= list.name %></h5>
      </div>
      <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
        <%= link_to list_path(list), class:"btn btn-primary hover:text-primary " do %>
        <%= list.name %>
        <% end %>
    </div>
    <% end %>
  </div>
</div>

app/views/lists/new.html.erb
<div class="container">
  <h1>New List</h1>
  <%= render 'form', list: @list %>
</div>

app/views/lists/show.html.erb
<div class="container">
    <h1 class="text-center"> <strong><%= @list.name.upcase %></strong></h1>
    <%= link_to "Add country",  new_list_review_path(@list), class: 'text-decoration-none text-center' %>
    <br>
      <ul>
      <% @list.countries.each do |country| %>
      <% review = Review.find_by(list: @list, country: country) %>
        <li class="list-unstyled">
          <h5><strong><%= country.name %></strong>
          <%= link_to review_path(review), method: :delete do %>
            <i class="fa-solid fa-trash"></i>
          <% end %></h5>
          <%= country.reviews.last.comment %> <br>
          <em><%= country.reviews.last.user_name %></em>
        </li>
      <% end %>
      </ul>
    <div class="d-flex gap-3">
    <%= link_to "Destroy this list", @list, method: :delete, class: 'btn btn-primary mt-3' %>
    <%= link_to "Update this list", edit_list_path(@list), class: 'btn btn-primary mt-3' %>
    </div>
</div>

app/views/reviews/_form.html.erb
<div class="container">
  <%= simple_form_for [@list, @review] do |f| %>
    <%= f.error_notification %>
    <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

    <div class="form-inputs">
      <%= f.association :country, collection: Country.all %>
      <%= f.input :user_name %>
      <%= f.input :comment %>
    </div>

    <div class="form-actions">
      <%= f.button :submit, class: 'btn btn-primary' %>
    </div>
  <% end %>
</div>

app/views/reviews/new.html.erb
<div class="container py-5">
  <div class="row">
    <div class="col-12 col-md-6 offset-lg-3">
      <div class="bg-white rounded p-3 shadow">
        <h3>Add a country to your <%= @list.name %> list</h3>
        <%= render 'form', list: @list, bookmark: @bookmark %>
      </div>
    </div>
  </div>
</div>